language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "cBwggVewCdlPUWx7mWxT8qo26GhwCLLFajZlrfL8wb2xKcLWwnEK1EuunCozgkGYISy5BWZkeMwF7hAdjxCRXAiHLHW1+BZiKz/ImAQRiKTZoktX9iqI/wqGeXzT9b/6v25IrN1hgdjrWmJ7wf+/Rxnwom1tYB1vzVnwzwSHFUt8pNr73a6KCfqRhwk+vilLN0rmT1Q/4f3ELWJegh3aDrbhSTM9BagI90T9vMBJ31XRMSiP/CG3P3sC4ZgzgNkb5CmmQmUBZef8167U0szBAdrzhszaiPq6XuLtvZ1gEg2/nAKwoZFQvmLGlA7rL4xUeB+X/jh/m0T9GbqDb61SBCRuP1LZR2v68wgnYeYOUjPAp2ZwNZURrFqE9PizyYJmy8LMUlqiN3nid8AgWDx7Q0rLw34lpGwZepJIh3Dy0vFBI4IQMwAnKfFV0EXFeI8dLMBYg0ClDiQV0dnaheySd+2LpZ65zv040nUyeZOc/TlREcgQ1i+OwaUtCtRYAXabLgP81d5rvDw5Ocqw+1ST2bznvOnds3o71WFPSJw1cTgfW7a1YCAPGvjMZTGdaZ4YwcVe5mBts7tITJ60ow4+Imp+bJ3y4N1mJA1xaT28fDWwGhetrVxcw1LpeZh55kY1mLYXRhAYDnJQMcOLpfJW07IEly4E5Pk4X8n9c3hSMLs="
env:
  secure: "HVFLOA5zj1Xy3eTjbEJQirhCwX6GR/tYGPzhHNkSFM6Yu9vT1SGpRCo0lDKpesZv/7MLphdMtD01H4fOrkJxIXal2fBjs1afMJYsHFoWQ9l9OemlG/Ykw2Y55vafEeuS2pZgMKlJtsDCW9wjMlBGTldbhIB0q2amy/nloPgh6b6oUQl4e6O5NRMx5kqOd0CiA0cxA0pRsv/8zGA7tKFnfTRYpR9189VNFgnXOG3/TwqnoGFuo3WCZmrOHuXM0VNFmAmk+GM/DfqDTvAtSL2UjRo3hRF+TRmJJY56kKRXk/yll8iOviu6MNC7WSaEvKu2nbTftFALASFDszYKZ8VsLSEvfVPSoN9L9xTYkdwIy30uZuS+kLUBIeVqME5KnIGN3IDO7zMxp7fHpymrSh5UjSk5KkrIxx5kePUOfaXF5PrZL8AIr4OsG7uaNOKoAlRp45UyzpoMVPbKGMEHI68LN7j+HmoJPMIcYhH8iMihLLI5Oa3VdwbrBZYqo+wCQJDNuSizGf8o3RZThvnPPTVw6Bqprz5k5Ygx5VQxE1hmMqnq1hpUSZkpXz4Qcgwkjlszk4ye+rYrC2F3tGINdpUyU3q15UcPx1x1jkam+bgZEdwFxsjZs3AWz8UDWygN6t9G83PfpMANaxYD2A9D5rkoMhONrFV5DuVY7uwzbnsroG4="
