language: node_js
node_js:
- '8'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "HVFLOA5zj1Xy3eTjbEJQirhCwX6GR/tYGPzhHNkSFM6Yu9vT1SGpRCo0lDKpesZv/7MLphdMtD01H4fOrkJxIXal2fBjs1afMJYsHFoWQ9l9OemlG/Ykw2Y55vafEeuS2pZgMKlJtsDCW9wjMlBGTldbhIB0q2amy/nloPgh6b6oUQl4e6O5NRMx5kqOd0CiA0cxA0pRsv/8zGA7tKFnfTRYpR9189VNFgnXOG3/TwqnoGFuo3WCZmrOHuXM0VNFmAmk+GM/DfqDTvAtSL2UjRo3hRF+TRmJJY56kKRXk/yll8iOviu6MNC7WSaEvKu2nbTftFALASFDszYKZ8VsLSEvfVPSoN9L9xTYkdwIy30uZuS+kLUBIeVqME5KnIGN3IDO7zMxp7fHpymrSh5UjSk5KkrIxx5kePUOfaXF5PrZL8AIr4OsG7uaNOKoAlRp45UyzpoMVPbKGMEHI68LN7j+HmoJPMIcYhH8iMihLLI5Oa3VdwbrBZYqo+wCQJDNuSizGf8o3RZThvnPPTVw6Bqprz5k5Ygx5VQxE1hmMqnq1hpUSZkpXz4Qcgwkjlszk4ye+rYrC2F3tGINdpUyU3q15UcPx1x1jkam+bgZEdwFxsjZs3AWz8UDWygN6t9G83PfpMANaxYD2A9D5rkoMhONrFV5DuVY7uwzbnsroG4="
